### ISSUE TITLE
Latest development branch - Issue at import lightbulb command

### ISSUE THREAD

**Issue by sag-6** [tandemdude/hikari-lightbulb#198] opened 2022-01-30 14:31 UTC
### Steps to reproduce

With the latest development branch I'm facing an issue at the `import lightbulb` command itself. I'm seeing a `AttributeError: module 'hikari' has no attribute 'AutocompleteInteraction'`. This was resolved when I installed older version of the development branch.

**Replication:**
1. Install latest lightbulb development branch from git. 
  `pip install git+https://github.com/tandemdude/hikari-lightbulb@development`
2. Use `import lightbulb` in your code.
3. You'll get an error when you run your code.
![image](https://user-images.githubusercontent.com/67011477/151703801-72fa8dea-09de-400f-ae1b-fe6dcd3f4b75.png)

### Expected result

There shouldn't be any error at `import lightbulb` command when development branch is used

### Actual result

With the current version we are getting `AttributeError: module 'hikari' has no attribute 'AutocompleteInteraction'` error.

**Error's Traceback:**
`Traceback (most recent call last):
  File "C:\DiscordBot\bot.py", line 3, in <module>
    import lightbulb
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages
\lightbulb\__init__.py", line 153, in <module>
    from lightbulb import app
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages
\lightbulb\app.py", line 42, in <module>
    from lightbulb import decorators
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages
\lightbulb\decorators.py", line 39, in <module>
    [hikari.CommandInteractionOption, hikari.AutocompleteInteraction],
AttributeError: module 'hikari' has no attribute 'AutocompleteInteraction'`

![image](https://user-images.githubusercontent.com/67011477/151703922-dc12328f-0c8c-4f81-8705-dc3605df83bd.png)

### System info

```shell
python -m lightbulb output:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Python\Python310\lib\site-packages\lightbulb\__init__.py", line 153, in <module>
    from lightbulb import app
  File "C:\Python\Python310\lib\site-packages\lightbulb\app.py", line 42, in <module>
    from lightbulb import decorators
  File "C:\Python\Python310\lib\site-packages\lightbulb\decorators.py", line 39, in <module>
    [hikari.CommandInteractionOption, hikari.AutocompleteInteraction],
AttributeError: module 'hikari' has no attribute 'AutocompleteInteraction'
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment] 2022-01-30 14:32
This is not a bug. All features have been merged into development in preparation for hikari 2.0.0dev106. Install hikari from their master branch if you want the features.

**Closed by tandemdude** 2022-01-30 14:32 UTC
Labels: bug

**Comment by sag-6** [comment] 2022-01-30 14:35
Ohh my bad.... sorry for false alarm. Should've double checked before submitting it.
